"""Add user_sessions table

Revision ID: 055142b6d9c1
Revises: c6391e8ce0a6
Create Date: 2025-06-26 19:26:44.770755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055142b6d9c1'
down_revision = 'c6391e8ce0a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'LOGGED_OUT', 'REVOKED', name='sessionstatusenum'), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['contas.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='contas'
    )
    op.create_index(op.f('ix_contas_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False, schema='contas')
    op.create_index(op.f('ix_contas_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True, schema='contas')
    op.create_index(op.f('ix_contas_user_sessions_status'), 'user_sessions', ['status'], unique=False, schema='contas')
    op.create_index(op.f('ix_contas_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='contas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contas_user_sessions_user_id'), table_name='user_sessions', schema='contas')
    op.drop_index(op.f('ix_contas_user_sessions_status'), table_name='user_sessions', schema='contas')
    op.drop_index(op.f('ix_contas_user_sessions_session_token'), table_name='user_sessions', schema='contas')
    op.drop_index(op.f('ix_contas_user_sessions_expires_at'), table_name='user_sessions', schema='contas')
    op.drop_table('user_sessions', schema='contas')
    # ### end Alembic commands ###