"""add roles and permissions system

Revision ID: 0db660442dab
Revises: 32a99bed3505
Create Date: 2025-06-26 20:22:41.380882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db660442dab'
down_revision = '32a99bed3505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='contas'
    )
    op.create_index(op.f('ix_contas_permissions_action'), 'permissions', ['action'], unique=False, schema='contas')
    op.create_index(op.f('ix_contas_permissions_name'), 'permissions', ['name'], unique=True, schema='contas')
    op.create_index(op.f('ix_contas_permissions_resource'), 'permissions', ['resource'], unique=False, schema='contas')
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='contas'
    )
    op.create_index(op.f('ix_contas_roles_name'), 'roles', ['name'], unique=True, schema='contas')
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['contas.permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['contas.roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='contas'
    )
    op.create_table('user_organization_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['contas.users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['contas.organizations.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['contas.users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['contas.roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['contas.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='contas'
    )
    op.create_index(op.f('ix_contas_user_organization_roles_organization_id'), 'user_organization_roles', ['organization_id'], unique=False, schema='contas')
    op.create_index(op.f('ix_contas_user_organization_roles_role_id'), 'user_organization_roles', ['role_id'], unique=False, schema='contas')
    op.create_index(op.f('ix_contas_user_organization_roles_user_id'), 'user_organization_roles', ['user_id'], unique=False, schema='contas')
    op.drop_constraint(op.f('organizations_owner_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'], source_schema='contas', referent_schema='contas')
    op.drop_constraint(op.f('user_organizations_organization_id_fkey'), 'user_organizations', type_='foreignkey')
    op.drop_constraint(op.f('user_organizations_user_id_fkey'), 'user_organizations', type_='foreignkey')
    op.create_foreign_key(None, 'user_organizations', 'organizations', ['organization_id'], ['id'], source_schema='contas', referent_schema='contas')
    op.create_foreign_key(None, 'user_organizations', 'users', ['user_id'], ['id'], source_schema='contas', referent_schema='contas')
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], source_schema='contas', referent_schema='contas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', schema='contas', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_organizations', schema='contas', type_='foreignkey')
    op.drop_constraint(None, 'user_organizations', schema='contas', type_='foreignkey')
    op.create_foreign_key(op.f('user_organizations_user_id_fkey'), 'user_organizations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_organizations_organization_id_fkey'), 'user_organizations', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'organizations', schema='contas', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_owner_id_fkey'), 'organizations', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_contas_user_organization_roles_user_id'), table_name='user_organization_roles', schema='contas')
    op.drop_index(op.f('ix_contas_user_organization_roles_role_id'), table_name='user_organization_roles', schema='contas')
    op.drop_index(op.f('ix_contas_user_organization_roles_organization_id'), table_name='user_organization_roles', schema='contas')
    op.drop_table('user_organization_roles', schema='contas')
    op.drop_table('role_permissions', schema='contas')
    op.drop_index(op.f('ix_contas_roles_name'), table_name='roles', schema='contas')
    op.drop_table('roles', schema='contas')
    op.drop_index(op.f('ix_contas_permissions_resource'), table_name='permissions', schema='contas')
    op.drop_index(op.f('ix_contas_permissions_name'), table_name='permissions', schema='contas')
    op.drop_index(op.f('ix_contas_permissions_action'), table_name='permissions', schema='contas')
    op.drop_table('permissions', schema='contas')
    # ### end Alembic commands ###