"""Update is_active default to False

Revision ID: 2f2e4ef6cc4f
Revises: a12a0a877ae3
Create Date: 2025-06-25 21:31:06.224485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2e4ef6cc4f'
down_revision = 'a12a0a877ae3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add default value False to is_active column
    op.alter_column('users', 'is_active',
                    existing_type=sa.Boolean(),
                    server_default=sa.text('false'),
                    schema='contas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove default value from is_active column
    op.alter_column('users', 'is_active',
                    existing_type=sa.Boolean(),
                    server_default=None,
                    schema='contas')
    # ### end Alembic commands ###