"""add organizations table and user_organizations association

Revision ID: 32a99bed3505
Revises: 055142b6d9c1
Create Date: 2025-06-26 19:54:43.672209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32a99bed3505'
down_revision = '055142b6d9c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['contas.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='contas'
    )
    op.create_index(op.f('ix_contas_organizations_name'), 'organizations', ['name'], unique=False, schema='contas')
    op.create_index(op.f('ix_contas_organizations_owner_id'), 'organizations', ['owner_id'], unique=False, schema='contas')
    op.create_table('user_organizations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['contas.organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['contas.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id'),
    schema='contas'
    )
    op.drop_constraint(op.f('user_sessions_user_id_fkey'), 'user_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'], source_schema='contas', referent_schema='contas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', schema='contas', type_='foreignkey')
    op.create_foreign_key(op.f('user_sessions_user_id_fkey'), 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_table('user_organizations', schema='contas')
    op.drop_index(op.f('ix_contas_organizations_owner_id'), table_name='organizations', schema='contas')
    op.drop_index(op.f('ix_contas_organizations_name'), table_name='organizations', schema='contas')
    op.drop_table('organizations', schema='contas')
    # ### end Alembic commands ###