"""rev1

Revision ID: 6cca279fc8b6
Revises: 2f2e4ef6cc4f
Create Date: 2025-06-25 21:50:27.196921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cca279fc8b6'
down_revision = '2f2e4ef6cc4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpf')
    # ### end Alembic commands ###