"""Initial migration2

Revision ID: a12a0a877ae3
Revises: 68a863bfa6e3
Create Date: 2025-06-25 21:26:00.991556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a12a0a877ae3'
down_revision = '68a863bfa6e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='contas'
    )
    op.create_index(op.f('ix_contas_users_email'), 'users', ['email'], unique=True, schema='contas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contas_users_email'), table_name='users', schema='contas')
    op.drop_table('users', schema='contas')
    # ### end Alembic commands ###